#
# Makefile for all kinds of Fingerprint
#


obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
#obj-y += goodix3c/
#obj-y += fpc/
obj-$(CONFIG_SUNWAVE_FINGERPRINT) += sunwave_driver_all_in_one/
obj-$(CONFIG_MTK_FINGERPRINT_SUNWAVECORP) += sunwave_driver_all_in_one/

